### PR TITLE
add cirrus CI

### PR DESCRIPTION
**Pull request by hv15**
Due to Travis' time limits, it difficult to build the whole Stdlib.

This PR moves to using [Cirrus CI](https://cirrus-ci.org) which provide some of the same features as Travis, but additionally:  
 * we can use our own docker containers, which saves a lot of time in setting up the build environment.
 * the time limit for building is user set... no more nasty killing
 * can be used to build on MacOS (but first we need our own hardware)

### CODE REVIEW

**Comment by hv15** [comment]
This PR replaces PR #26 as Drone CI was not behaving nicely.

**Comment by fkorotkov** [comment]
FYI you can run macOS builds for OSS for free on community infrastructure: https://cirrus-ci.org/guide/macOS/

**Comment by hv15** [comment]
@fkorotkov that's awesome, thanks!

**Comment by hv15** [comment]
superseded by #35.

**Pull request closed without merging**
