### PR TITLE
get name from mkstemp

### PR DESCRIPTION
**Pull request by hv15**
the existing implementation missed out that we can get the temp file
name from the function. This commit extends mkstemp to return this.

I feel that with MR this is room for improvement:
- `mktemp.c` is messy, this needs to be cleaned up
- also, we should be refcounting the new string we get returned. I can't remember the `#pragma` for this, and suggestions?

### CODE REVIEW

**Comment by hv15** [comment]
This fix was motivated by a fix I making to the PNG module, which still uses `tmpnam` which is considered unsafe.

**Comment by hv15** [comment]
if everything is fine, please merge :)

**Comment by ashinkarov** [comment]
Isn't this new `name` that you allocate on the C side is a guaranteed memory leak?
I don't remember the details but I thought that you need to create an array descriptor explicitly and then use `SAC_ND_{INC,DEC}_RC_*` macros to fiddle around with the descriptor.  Have a look at the PNG library and maybe consult Bodo?  It would be good if we can convince ourselves that the memory leak doesn't happen.  Maybe add a quick comment on memory management for `name`?

Also, it seems that `template` is readonly; would it make sense to mark it `const` in the C file?

**Comment by hv15** [comment]
So I've changed the implementation to use `SAC_ND_PARAM_*` macros to correctly pass the descriptor and perform reference counting. We allocate the `name` string within the function and set RC to 1. Testing with the [attached program](https://github.com/SacBase/Stdlib/files/3908577/mkstemp-test.sac.txt) gives the expected outcome, e.g. create temp file and return it's name. The generated code also looks sane, by inspecting we seem to dec-rc/free `name` just after printing it out.

**Pull request merged**
