### PR TITLE
Correct show() on scalars. Emend array formatting a little bit.

### PR DESCRIPTION
**Pull request by hv15**

### CODE REVIEW

**Comment by hv15** [comment]
@bernecky your build failed, have a look at https://github.com/SacBase/Stdlib/pull/48/checks?check_run_id=1866372937.

**Comment by hv15** [comment]
lol, completely missed that this was here... @bernecky which should we push for merging in, these changes or the ones from MR #57?

**Comment by bernecky** [comment]
I have no idea which is correct. Let's do the one-line fix for now.

**Review by bernecky — APPROVED** [review]

**Comment by bernecky** [comment]
I am looking at format() and show() semantics now, and will repair anything that is wrong there.
I will copy the relevant apex UnitTest code into the Stdlib unit test home, once I find it.

I am unable to deal with print(), as I have no idea where to find its SaC specification or unit tests.

**Pull request merged**
