### PR TITLE
Add Travis

### PR DESCRIPTION
**Pull request by hv15**
This series of commits allows us now to build the StdLib on Travis - this is particular useful for pull-requests as it means we now have a means to verify requests actually build **without** errors or warnings.

A few notes about the setup:
-  Because Travis.org sets a hardlimit of 50 minutes for builds, we only build `mt_pth` target, as this takes less than 40 minutes. We also reduce the linksetsize to 250 in order *not* to run out of memory. Having said that, we do build the complete stdlib (core + extras).
- We use the Debian release version of sac2c (http://www.sac-home.org/doku.php?id=download:main) which is somewhat old now - my tests show that everything builds, so I think we are safe, but it means that potentially newer features will not be compiled as these are not supported by the compiler.

### CODE REVIEW

**Comment by hv15** [comment]
FYI, the first Travis run will fail here because I did not pull in @sbscholz latest commits....

**Comment by hv15** [comment]
Please ignore current travis result as this is a false-positive... remeding now...

**Comment by ashinkarov** [comment]
It seems that we are missing yet another xinstall target in CmakeLists.txt in sac2c.  This one:
```
XINSTALL (DIRECTORY "${PROJECT_BINARY_DIR}/include/libsac"
  DESTINATION "${INCPATH_INSTALL}"
  COMPONENT headers)
```
Adding this and releasing 1.3.2 should fix the problem.
Maybe we should think about better description of the header files in cmake files, so that in future we wouldn't miss stuff like this.

**Comment by sbscholz** [comment]
hmmmm I thought that everything under include was taken anyways?!
otherwise, we need to add include/runtime as well…

Bodo

**Comment by hv15** [comment]
Aye, noticed that just yesterday. Will push to sac2c now...

**Comment by ashinkarov** [comment]
Why the hell the last travis run failed?  I don't see any errors or warnings, it is just complaining that:
```sh
The command "make -j3 2>&1 | tee build.log" exited with 0.

$ travis_assert ${PIPESTATUS[0]}

The command "travis_assert ${PIPESTATUS[0]}" failed and exited with 1 during .
```
any ideas what is wrong with `PIPESTATUS`?

**Comment by hv15** [comment]
Ok, so I've had a closer look at what travis does. Each line within a `script:` section is run as a separate bash process. They do some sort of state propagation, but `$PIPESTATUS` is not carried. This is significant as, similar to `$?`, it only holds information on the last pipe operation. If it's called without there having been a pipe operation, per-spec its default value is empty (which in a number context is the same as zero). Ok, so that seems fine - well no because the actual implementation does not guarantee this - it cab get really weird (as per [BASH variables](http://tldp.org/LDP/abs/html/internalvariables.html)). `$PIPESTATUS` is known to have very strange behaviour when read without there having been a pipe command *directly* beforehand. It can contain almost anything. Observe the following strangeness:

```sh
$ if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "hello"; fi
$ if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "hello"; fi
hello
$ echo "what the duck"
what the duck
$ false | true
$ if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "hello"; fi
hello
$ true | true
$ if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "hello"; fi
```

_This is why `travis_assert` fails._

I use this same technic in the GitLab CI stuff, and there it works - the reason for this is that the entire `script:` section is executed as a single block rather then line-by-line... not sure why Travis decided to do it that way.

The solution then is to call `travis_assert` inline with the `make` operation, e.g. `make -j3 2>&1 | tee build.log; travis_assert ${PIPESTATUS[0]}`. See latest (and greatest) commit.

**Comment by ashinkarov** [comment]
Yeeey! It works, merging this in.

**Pull request merged**
